### ISSUE TITLE
Broke?

### ISSUE THREAD

**Issue by Schknheit** [mprey/steam-account-creator#4]
Did it just broke?

**Comment by PlantronicsGamer** [comment]
`client.createAccount(username,` password, email, function (result) {` is broken (Error: 20)

**Comment by Valvecorp** [comment]
Unfortunately, the registration function as it seemed to you earlier was very simple, we decided to improve it a little, testing was conducted as early as 2017 on some zones around the world, and we really enjoyed it, since there are too many bots, in steam in the past we decided to make a restriction on which for a long time there was a speech (please note that we do not limit the number of registrations, we restrict only the method of registering them)

**Comment by Schknheit** [comment]
Ok @Valvecorp, great thing talking about bots but... why your account was created 3hours ago? Good try sir.

**Comment by Valvecorp** [comment]
@Schknheit not when it's not too late) and immediately explain the situation, I'm not an official representative

**Comment by Schknheit** [comment]
Good to know, also in the west nobody uses ")" to represent a smile. Good try mother russia.

**Comment by Valvecorp** [comment]
Nobody said that I was from the west)

**Comment by Schknheit** [comment]
> https://github.com/mprey/steam-account-creator/issues/4#issuecomment-358621456

ok then...
